config/projects/harmony.rb
config/software/discord.rb

Geez.. did I take the naming schema a little far? Maybe.
The discord-0.0.1 tarball is comprised of: https://gist.github.com/curiositycasualty/d83016b7f1bcc865354b

Add discord to harmony

---

config/software/popt.rb
config/software/rsync.rb

Required to get the build to pass on ppc64 platforms.
@chef/engineering-services

Update config guess

---

config/projects/harmony.rb

Add rpm package signing to harmony project
@chef/engineering-services

Fix rpm package signing

---

.expeditor/config.yml

Signed-off-by: Jaymala Sinha <jsinha@chef.io>
@tduffield @chef/engineering-services

Add expeditor config to test subscription

---

.expeditor/config.yml
.github/CODEOWNERS

Signed-off-by: Seth Chisamore <schisamo@chef.io>

Send all notifications to the BEN team

---

.expeditor/config.yml

Signed-off-by: Jaymala Sinha <jsinha@chef.io>

Enable Expire Cache Label in expeditor configuration

---

package-scripts/harmony/postinst
package-scripts/harmony/postrm

Signed-off-by: Jaymala Sinha <jsinha@chef.io>

Test exp cache build

---

.kitchen.yml

Signed-off-by: Jaymala Sinha <jsinha@chef.io>

Test expire cache build final

---

.expeditor/config.yml

Add beta buildkite pipeline omnibus builds

---

.expeditor/adhoc.omnibus.yml
config/projects/harmony.rb

Signed-off-by: Tom Duffield <tom@chef.io>

Update MSI package config with latest details + platform matrix update

---

config/projects/harmony.rb
omnibus.rb

Also brings the logic closer to what we use in Chef Infra Client

Minor updates to fix some build errors

---

.expeditor/adhoc-canary.omnibus.yml
.expeditor/config.yml

Remove esoteric platforms from adhoc pipeline

---

omnibus/config/projects/harmony.rb

Fix license_file

---

.expeditor/adhoc-canary.omnibus.yml
.expeditor/adhoc.omnibus.yml

Signed-off-by: Nathaniel Kierpiec <nkierpiec@chef.io>

Update test path for shim pipeline def

---

.expeditor/adhoc-canary.omnibus.yml
.expeditor/adhoc.omnibus.yml

Add test-path-windows to omnibus pipeline shims

---

omnibus/Gemfile

Signed-off-by: Tom Duffield <github@tomduffield.com>

Use new env var in omnibus/Gemfile

---

.expeditor/adhoc-canary.omnibus.yml
.expeditor/adhoc.omnibus.yml
omnibus/omnibus-test.ps1
omnibus/omnibus-test.sh

Edited test scripts to accommodate for multiple package locations based on how the pipelines were run
Signed-off-by: Nathaniel Kierpiec <nkierpiec@chef.io>

Update shim pipeline files with skip-artifactory-platforms

---

.expeditor/adhoc-canary.omnibus.yml
.expeditor/adhoc.omnibus.yml

Signed-off-by: Tom Duffield <github@tomduffield.com>

Add FreeBSD 13 testers

---

omnibus/omnibus-test.ps1
omnibus/omnibus-test.sh

Remove the local install logic. Also, fix the Windows tests.

Remove Install Logic

---

.expeditor/adhoc-canary.omnibus.yml
.expeditor/adhoc.omnibus.yml
.github/CODEOWNERS

Remove macos 10.14 from build matrix

---

.expeditor/config.yml
.expeditor/release.omnibus.yml

Signed-off-by: Michael Maslanka <maslanka@progress.com>

Make release version test

---

.expeditor/config.yml
.expeditor/scripts/verify/build_package.sh
.expeditor/verify.pipeline.yml
habitat/config/client.rb
habitat/hooks/init
habitat/plan.ps1

testing hab aarch64 build process

---

omnibus/config/projects/harmony.rb

Package signing certificate has been renewed two months ago as part of "CHEF-14426". Omnibus/Harmony has been missed back then, so it needs to be updated to reflect the changes.

Updated signing certificate thumbprint

---

.expeditor/build.habitat.yml
habitat/plan.sh

changing origin

---

.expeditor/build.habitat.yml
.expeditor/config.yml
habitat/plan.sh

Sean simmons progress/hab origin change

---

.expeditor/config.yml

I still think I have to manually add a channel manually to habitat
https://docs.chef.io/habitat/habitat_cli/#hab-bldr-channel-create

adding workloads to match up the artifact channels and subscriptions

---

.expeditor/config.yml
README.md
habitat/plan.sh

Sean simmons progress/boot strap bldr channels

---

.expeditor/config.yml
.expeditor/habitat-export.pipeline.yml

Sean simmons progress/chef 16390 hab export upload s3

---

.expeditor/config.yml

testing symantec versioning

---

.expeditor/config.yml

testing out promotion events

---

.expeditor/config.yml

testing publish rubygem

---

.expeditor/config.yml
.expeditor/scripts/promote-hab-pkgs.sh

Sean simmons progress/habworkflowtesting2

---

.expeditor/config.yml

updating configuration

---

.expeditor/config.yml

attempting to build in some auto promotion events

---

.expeditor/build.habitat.yml
.expeditor/config.yml
.expeditor/scripts/promote-hab-pkgs.sh

adding vars to see what we get

---

.expeditor/scripts/promote-hab-pkgs.sh

updating script

---

.expeditor/scripts/promote-hab-pkgs.sh

Sean simmons progress/hab env testing

---

.expeditor/config.yml

enabling all workloads for the final round of testing

---

.expeditor/config.yml

adding a new config for now

---

.expeditor/scripts/promote-hab-pkgs.sh

updating promote script

---

.expeditor/config.yml
.expeditor/scripts/promote-hab-pkgs.sh

this seems like it will be the easier way to handle multiple channels

with working with two release channels

---

.expeditor/config.yml
.expeditor/scripts/promote-hab-pkgs.sh

updating staging area and script for promote

---

.expeditor/config.yml

testing this workflow with hab_package_published

---

.expeditor/scripts/promote-hab-pkgs.sh

updating now that its valid

---

.expeditor/config.yml

updating action with bash and trigger pipeline

---

.expeditor/scripts/promote-hab-pkgs.sh

updating file to remove debug statements

---

.expeditor/config.yml

testing promote first build

---

.expeditor/config.yml
.expeditor/scripts/promote-hab-pkgs.sh

Sean simmons progress/promote first channel auto

---

.expeditor/scripts/promote-hab-pkgs.sh

updating script based off of env vars we see

---

.bldr.toml
.expeditor/config.yml

testing configuration

---

.expeditor/config.yml

testing upload to rubygems.org instead

---

.expeditor/config.yml

testing expeditor configuration

---

.expeditor/config.yml

testing config

---

.expeditor/config.yml

ci: changes to expeditor config to publish rubygems

---

.expeditor/config.yml

ci: change expeditor config to check if we can publish to rubygemschef

---

OmnibusHarmony-Test-Gem.gemspec

chore: undo changes to gemspec

---

.expeditor/config.yml

ci: temporarily disable promoting to hab bldr

---

.expeditor/config.yml
CHANGELOG.md

introduce changelog tracking by expeditor

---

CHANGELOG.md

chore: manual changelog update
